apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: blue-green
spec:
  selector:
    app: blue-green-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
